source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KPProgressImageView_Example', :exclusive => true do
  pod "KPProgressImageView", :path => "../"
end

target 'KPProgressImageView_Tests', :exclusive => true do
  pod "KPProgressImageView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
